# Generated by Django 4.1.2 on 2022-10-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
        migrations.AddField(
            model_name='contact',
            name='problem',
            field=models.CharField(default='m', max_length=500),
        ),
    ]
